name: Create Azure Resources

on:
  push:
    branches:
      - main
    paths:
      - 'bicep/**/*.bicep'
      - '.github/workflows/deploy-infra.yml'
  workflow_dispatch:    

jobs:
  create-azure-resources:

    env:
      DEPLOYMENT_NAME: apim-deployment
      REGION: 'eastus' # You can change this to reflect the region where you deploy your resources

    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v2

      - name: Validate that bicep builds
        run: az bicep build -f main.bicep
        working-directory: ./bicep

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}          

      - name: deploy
        id: createResources
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          scope: subscription
          region: ${{ env.REGION }}
          deploymentName:  ${{ env.DEPLOYMENT_NAME }}
          template: ./bicep/main.bicep
          parameters: ./bicep/main.parameters.json publisherEmail=${{ secrets.PUBLISHER_EMAIL }} publisherName=${{ secrets.PUBLISHER_NAME }}

        # https://learn.microsoft.com/en-us/azure/api-management/api-management-howto-mutual-certificates#self-signed-certificates
      - name: Disable chain validation Azure APIM
        run: |
          Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force
          $context = New-AzApiManagementContext -resourcegroup ${{ steps.createResources.outputs.spokeRgName }} -servicename ${{ steps.createResources.outputs.apimName }}
        shell: pwsh
                    

                        


    